version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - servidor1
      - servidor2
      - servidor3
      - servidor4
      - servidor5
  servidor1:
    container_name: Servidor1
    build:
      context: ./Servidor1
      dockerfile: Dockerfile
    ports:
      - 5001:5000
  servidor2:
    container_name: Servidor2
    build:
      context: ./Servidor2
      dockerfile: Dockerfile
    ports:
      - 5002:5000
  servidor3:
    container_name: Servidor3
    build:
      context: ./Servidor3
      dockerfile: Dockerfile
    ports:
      - 5003:5000
  servidor4:
    container_name: Servidor4
    build:
      context: ./Servidor4
      dockerfile: Dockerfile
    ports:
      - 5004:5000
  servidor5:
    container_name: Servidor5
    build:
      context: ./Servidor5
      dockerfile: Dockerfile
    ports:
      - 5005:5000